language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
  - submodules/poa-web3-1.0

env:
  - TEST_SUITE=e2eMintedUI
  - TEST_SUITE=e2eMintedWhitelist
  - TEST_SUITE=e2eMintedMincap
  - TEST_SUITE=e2eDutchUI
  - TEST_SUITE=e2eDutchWhitelist
  - TEST_SUITE=e2eDutchMincap
  - TEST_SUITE=reactComponentTests
  - TEST_SUITE=contractsMinted
  - TEST_SUITE=contractsDutchPart1
  - TEST_SUITE=contractsDutchPart2
  - TEST_SUITE=contractsDutchPart3
  - TEST_SUITE=contractsDutchPart4

install:

before_script:
  - git submodule update --init --recursive --remote
  - npm run installWeb3
  - bash ./scripts/generateProxyContracts.sh
  - npm run moveTruffleConfigPublic
  - npm run moveSolcVersionOutputPublic
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:

  - if [ $TEST_SUITE == 'e2eMintedUI' ]; then npm run e2eMintedUI ; fi

  - if [ $TEST_SUITE == 'e2eDutchUI' ]; then npm run e2eDutchUI; fi


after_script:
  - sudo kill `sudo lsof -t -i:8545`


after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

